### ISSUE TITLE
Problem to prepare chatwoot db

### ISSUE THREAD

**Issue by zhiru** [willph/evolutionApi_chatwoot_docker#1]
problem to execute this parte of docs:

Wait while it compiles all the data. After completion, enter the following command:
````bash
docker-compose run --rm rails bundle exec rails db:chatwoot_prepare
````

here is the error:
<img width="502" alt="image" src="https://github.com/willph/evolutionApi_chatwoot_docker/assets/4226997/c54f2f04-6e50-467e-a91a-8ed320779bd4">

**Comment by willph** [comment]
precisa deletar e recria a pasta data com as duas pasta que tem dentro

**Comment by willph** [comment]
adicionei essa menção ao readme antes desse passo.

Obrigado por avisa

**Comment by willph** [comment]
> problem to execute this parte of docs:
> 
> Wait while it compiles all the data. After completion, enter the following command:
> 
> ```shell
> docker-compose run --rm rails bundle exec rails db:chatwoot_prepare
> ```
> 
> here is the error: <img alt="image" width="502" src="https://user-images.githubusercontent.com/4226997/255304477-c54f2f04-6e50-467e-a91a-8ed320779bd4.png">

Por algum motivo que não consegui identificar ainda, fica precisando roda o comando 2x.
Se por acaso tiver experiência com docker e tiver um tempo disponível para envia uma PR, fico grato.

Também pode me encontra no grupo, quepasa e evolution.

Otima semana!
