### ISSUE TITLE
Error on evolutionApi

### ISSUE THREAD

**Issue by estebanlis** [willph/evolutionApi_chatwoot_docker#5]
Hi!
I've followed the steps you mentioned in the repository, but in the evolutionApi container, I get the following error:

```
/evolution/dist/src/main.js:142
evolution-api      |         server.listen(httpServer.PORT, () => logger.log(httpServer.TYPE.toUpperCase() + ' - ON: ' + httpServer.PORT));
evolution-api      |                ^
evolution-api      | 
evolution-api      | TypeError: Cannot read properties of undefined (reading 'listen')
evolution-api      |     at /evolution/dist/src/main.js:142:16
evolution-api      |     at Generator.next (<anonymous>)
evolution-api      |     at /evolution/dist/src/main.js:31:71
evolution-api      |     at new Promise (<anonymous>)
evolution-api      |     at __awaiter (/evolution/dist/src/main.js:27:12)
evolution-api      |     at bootstrap (/evolution/dist/src/main.js:61:12)
evolution-api      |     at Object.<anonymous> (/evolution/dist/src/main.js:157:1)
evolution-api      |     at Module._compile (node:internal/modules/cjs/loader:1155:14)
evolution-api      |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
evolution-api      |     at Module.load (node:internal/modules/cjs/loader:1033:32)
```
Thank you for your work.

**Comment by IZIme07** [comment]
The same

**Comment by willph** [comment]
It is out of date, this weekend I will be uploading the new version. but the project can be found at https://github.com/EvolutionAPI/evolution-api

I made these files to make installation and use easier.

Thanks for the messages.

**Comment by IZIme07** [comment]
> It is out of date, this weekend I will be uploading the new version. but the project can be found at https://github.com/EvolutionAPI/evolution-api
> 
> I made these files to make installation and use easier.
> 
> Thanks for the messages.

I was just about to use your solution because it brings everything I need together in Docker Compose (Chatwoot + Evolution API). I’m ready to give you a hug if you fix it, because I've been struggling for several days trying to rebuild it.

**Comment by willph** [comment]
Updated to Image of Nestor's Chatwoot v3.12.0 and Evolution API 2.0.10.
You can test in a test environment.

**Comment by IZIme07** [comment]
> Updated to Image of Nestor's Chatwoot v3.12.0 and Evolution API 2.0.10. You can test in a test environment.

```cp evolution-api/Docker/.env.example evolution-api/Docker/.env```
This command throws an error because the directory is not originally contained in the repository. And the chatwoot folder not include also. Create it manualy with data/postgres and data/redis

but unfortunately all the containers still did not start, in this case the error was related to postgres itself.
![image](https://github.com/user-attachments/assets/908bd738-00a0-4820-b02b-c7bd25ffb05c)

thanks for the help

**Comment by willph** [comment]
Thanks for letting me know

I put it like this cp evolution-api/.env.example evolution-api/.env

and it went unnoticed when I reviewed it

**Comment by willph** [comment]
> > Updated to Image of Nestor's Chatwoot v3.12.0 and Evolution API 2.0.10. You can test in a test environment.
> 
> `cp evolution-api/Docker/.env.example evolution-api/Docker/.env` This command throws an error because the directory is not originally contained in the repository. And the chatwoot folder not include also. Create it manualy with data/postgres and data/redis
> 
> but unfortunately all the containers still did not start, in this case the error was related to postgres itself.
> 
> thanks for the help

I did several tests and several modifications, now it is working ok.
Tests were performed on a free tier Oracle VPS with 1GB of RAM
